export default {
  baseURL: function(subDomain) {
    return 'http://' + subDomain + '.oscarhq-staging.com'
    // return 'http://' + subDomain + '.lvh.me:3000'
  },
  login: '/api/v1/auth/sign_in',
  updateTokenPath: '/api/v1/auth',
  tokenValidationPath: '/api/v1/auth/validate_token',
  clientsPath: '/api/v1/clients',
  enterNgoPath: '/api/v1/enter_ngos',
  exitNgoPath: '/api/v1/exit_ngos',
  domainPath: '/api/v1/domains',
  domainGroupsPath: '/api/v1/domain_groups',
  familiesPath: '/api/v1/families',
  birthProvincesPath: '/api/v1/birth_provinces',
  provincesPath: '/api/v1/provinces',
  districtsPath: '/api/v1/districts',
  communesPath: '/api/v1/communes',
  villagesPath: '/api/v1/villages',
  donorsPath: '/api/v1/donors',
  usersPath: '/api/v1/users',
  referralSourcesPath: '/api/v1/referral_sources',
  referralSourceCategoriessPath: '/api/v1/referral_sources/categories',
  tasksPath: '/api/v1/users',
  createTaskPath: '/api/v1/tasks',
  editTaskPath: '/api/v1/tasks',
  deleteTaskPath: '/api/v1/tasks',
  quantitativeTypesPath: '/api/v1/quantitative_types',
  agenciesPath: '/api/v1/agencies',
  logoutPath: '/api/v1/auth/sign_out',
  departmentsPath: '/api/v1/departments',
  assessmentsPath: '/api/v1/assessments',
  caseNotesPath: '/api/v1/case_notes',
  ngoPath: '/api/v1/organizations',
  settingPath: '/api/v1/settings',
  additionalFormPath: '/api/v1/custom_field_properties',
  programStreamsPath: '/api/v1/program_streams',
  editEnrollmentProgramPath: '/api/v1/clients/${client_id}/client_enrollments/${program_id}',
  createEnrollmentProgramPath: '/api/v1/clients/${client_id}/client_enrollments',
  editLeaveProgramPath: '/api/v1/clients/${client_id}/client_enrollments/${program_id}/leave_programs/${leave_id}',
  createLeaveProgramPath: '/api/v1/clients/${client_id}/client_enrollments/${program_id}/leave_programs',
  editTrackingProgramPath: '/api/v1/clients/${client_id}/client_enrollments/${client_enrollment_id}/client_enrollment_trackings/${id}',
  createTrackingPath: '/api/v1/clients/${client_id}/client_enrollments/${client_enrollment_id}/client_enrollment_trackings',
  createFamilyAdditonalFormPath: '/api/v1/families/${entity_id}/custom_field_properties',
  createClientAdditonalFormPath: '/api/v1/clients/${entity_id}/custom_field_properties',
  
  // NOTES: "removeFormBuilderAttachmentPath" doesn't in api/v1/.....*
  // It only in api/form_builder_attachments/....*
  removeFormBuilderAttachmentPath: 'api/form_builder_attachments/${file_id}?file_index=${file_index}&file_name=${file_name}' 
}
