# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new Alpha Build To Google PlayStore"
  lane :alpha do

    version_code = increment_version_code(
      gradle_file_path: './app/build.gradle'
    )

    gradle(task: "clean")

    gradle(
      task: "app:assemble",
      build_type: "Release"
    )

    supply(
      track: "alpha",
      apk: "./app/build/outputs/apk/release/app-release.apk",
      package_name: 'com.rotati.oscarhq.stagging',
      metadata_path: 'fastlane/metadata/android',
      json_key: './secure/api-6175533715952706835-208167-bd894bba2f4f.json',
    )


    git_commit(
      path: "./app/build.gradle",
      message: "Fastlane Android: Release new build version #{version_code}  [ci skip]"
    )
  
  end
end
